version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fullstack-auth-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: fullstack-auth-app
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fullstack-auth-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fullstack-auth-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/fullstack-auth-app
      - JWT_SECRET=super-secret-jwt-key-docker
      - JWT_EXPIRES_IN=7d
      - LOG_LEVEL=info
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./server/logs:/app/logs
    networks:
      - fullstack-auth-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: fullstack-auth-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - fullstack-auth-network

volumes:
  mongodb_data:

networks:
  fullstack-auth-network:
    driver: bridge
